// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab1.Data;

#nullable disable

namespace lab1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409134847_updateTopicsInCourse")]
    partial class updateTopicsInCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lab1.Models.Course", b =>
                {
                    b.Property<int>("crs_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("crs_Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumDegree")
                        .HasColumnType("int");

                    b.Property<string>("Topics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDegree")
                        .HasColumnType("int");

                    b.Property<string>("crs_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("crs_Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("lab1.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("lab1.Models.Ins_Course", b =>
                {
                    b.Property<int>("ins_Id")
                        .HasColumnType("int");

                    b.Property<int>("crs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Coursecrs_Id")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int?>("Instructorins_Id")
                        .HasColumnType("int");

                    b.HasKey("ins_Id", "crs_Id");

                    b.HasIndex("Coursecrs_Id");

                    b.HasIndex("Instructorins_Id");

                    b.ToTable("Ins_Courses");
                });

            modelBuilder.Entity("lab1.Models.Instructor", b =>
                {
                    b.Property<int>("ins_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ins_Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("ins_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ins_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ins_Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("lab1.Models.Stud_Course", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.Property<int>("crs_Id")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.HasKey("SSN", "crs_Id");

                    b.HasIndex("crs_Id");

                    b.ToTable("Stud_Courses");
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSN"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSN");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("lab1.Models.Ins_Course", b =>
                {
                    b.HasOne("lab1.Models.Course", "Course")
                        .WithMany("Ins_Courses")
                        .HasForeignKey("Coursecrs_Id");

                    b.HasOne("lab1.Models.Instructor", "Instructor")
                        .WithMany("ins_Courses")
                        .HasForeignKey("Instructorins_Id");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("lab1.Models.Instructor", b =>
                {
                    b.HasOne("lab1.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("lab1.Models.Stud_Course", b =>
                {
                    b.HasOne("lab1.Models.Student", "Student")
                        .WithMany("Stud_Courses")
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab1.Models.Course", "Course")
                        .WithMany("Stud_Courses")
                        .HasForeignKey("crs_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.HasOne("lab1.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("lab1.Models.Course", b =>
                {
                    b.Navigation("Ins_Courses");

                    b.Navigation("Stud_Courses");
                });

            modelBuilder.Entity("lab1.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("lab1.Models.Instructor", b =>
                {
                    b.Navigation("ins_Courses");
                });

            modelBuilder.Entity("lab1.Models.Student", b =>
                {
                    b.Navigation("Stud_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
